### ISSUE TITLE
:MiniBrowser not an editor command

### ISSUE THREAD

**Issue by still-dreaming-1** [rhysd/nyaovim-mini-browser#3]
Hello. I just installed NyaoVim using npm and then added this plugin. I set the nyovimrc.html file to match the example in the README. When I run `:MiniBrowser` it says E492 :MiniBrowser not an editor command. I did run the `:UpdateRemovePlugins` as well and restarted NyaoVim, so that is not the problem.

**Comment by still-dreaming-1** [comment]
I looked inside plugin/mini-browser.vim and found it is looking for `g:nyaovim_version`. I tried `echo exists('g:nyaovim_version')` which is 0. So I tried removing that part from the if. Now `:MiniBrowser` no longer causes the not an editor command message, but it does not seem to do anything.

**Comment by rhysd** [comment]
Could you show your `nyaovimrc.html`?

**Comment by still-dreaming-1** [comment]
Sure, I tried several different ways... Here is what I have now:

```
<dom-module id="nyaovim-app">
    <template>
        <style>
            /* CSS configurations here */
            .horizontal {
                display: flex;
                width: 100%;
                height: 100%;
            }
            neovim-editor {
                width: 100%;
                height: 100%;
            }
        </style>

        <!-- Put your component in flex box layout  -->
        <div class="horizontal">
            <neovim-editor id="nyaovim-editor" argv$="[[argv]]"></neovim-editor>
            <!-- <mini-browser editor="[[editor]]"></mini-browser> -->
            <mini-browser
              url="https://google.com"
              width="600"
              useragent="...(snip)"
              visible
            ></mini-browser>
        </div>
    </template>
</dom-module>
```

**Comment by rhysd** [comment]
Thanks.

Could you modify `neovim-editor` component as below?

``` html
<neovim-editor id="nyaovim-editor" argv="[[argv]]"></neovim-editor>
```

In Polymer 1.6, handling data binding was changed.  `$=` binding was removed and simple `=` binding looks available.  `nyaovimrc.html` initial template was already fixed, but local HTML which already exists previously can't be fixed so manual update is required.

**Comment by still-dreaming-1** [comment]
Thanks. I removed the `$`. The command still does not seem to do anything.

**Comment by still-dreaming-1** [comment]
I got it working! I set the `mini-browser editor` component back to the original thing that is shown at the top of the README: `<mini-browser editor="[[editor]]"></mini-browser>`
